### ISSUE TITLE
Rat,not working,shit gen . 

### ISSUE THREAD

**Issue by Mitsos04** [Its-Vichy/IOGen#3]
Shit gen. dont download -rep

**Comment by Its-Vichy** [comment]
Before saying that, learn to read :,) I am waiting to see where the "virus" is

**Comment by Its-Vichy** [comment]
![image](https://user-images.githubusercontent.com/66045929/154307886-c40c7383-0c8e-4337-9bb7-0bc2c558a1d0.png)
